### ISSUE TITLE
PC Engine - Japanese Final Match Tennis

### ISSUE THREAD

**Issue by throwingmuse** [byuu/byuu#17]
Japanese Final Match Tennis boots, allows selection screen setup, and then freezes when gameplay begins.

**Comment by byuu** [comment]
I can confirm this one. Looks like another hellish case of no obvious hanging ala Gaia no Monshou, but the game obviously never proceeds.

**Comment by FitzRoyX** [comment]
Chances are, there is a game that instahangs for the same reason that this game hangs at match start. In other words, the tracelog method favors looking at bugs that happen quickly first.

For example, Gaia no Monshou didn't instahang, but All-Star Power League did. They were both hanging for the same reason.

**Comment by byuu** [comment]
I fixed it in v3.2
