### ISSUE TITLE
[Mega Drive] Revenge of Shinobi black screen

### ISSUE THREAD

**Issue by jhlkek** [byuu/byuu#19]
Loading The Revenge of Shinobi (Rev B) gives a black screen and nothing else.

**Comment by byuu** [comment]
Works here. May've been fixed in a more recent WIP, may be a bad image being used, not sure ...

![Screenshot_2020-03-11_21-30-58](https://user-images.githubusercontent.com/2107894/76416898-4124a980-63df-11ea-937c-349f8daf13c6.png)
