### ISSUE TITLE
[PCE] Repeated lines in overscan areas

### ISSUE THREAD

**Issue by FitzRoyX** [byuu/byuu#20]
Aoi Blink, Fantasy Zone, Bikkuriman World, Darius Alpha and others have this issue of the top and/or bottom line of rendered scene being repeated.

![bikku](https://user-images.githubusercontent.com/57089001/76276683-7fda2880-6254-11ea-92ea-5243bca53478.png)
![aoi](https://user-images.githubusercontent.com/57089001/76276878-13135e00-6255-11ea-9d69-829eefeb4fba.png)

Also, PCE list can be found here: https://www.retrowide.com/stuff/byuu_compat.htm

**Comment by byuu** [comment]
Oh, I know exactly what's causing that. I'll fix it in the next WIP.

PC Engine is going to be a ride. The games are even more timing-sensitive than the SNES (*much* moreso in fact, it's madness), but the total scene knowledge stopped advancing around where SNES emulation was at in 1998.

Everyone either uses per-game hacks or has tons of broken games.

**Comment by FitzRoyX** [comment]
Well, at least it doesn't have crazy mappers or EEPROMS or FIFO. I might make a report for the missing graphics stuff as that also looks related. But I don't plan on inflating github with my buglists.

**Comment by byuu** [comment]
Fixed, will be in v2.7, thanks for the report.

Yeah I would prefer not having the issues all submitted here if you don't mind.

I want to make a proper bug tracker on my website where I can organize issues based on which emulator(s) it affects, severity, category, system, etc. We can also allow for things like feature requests and wishlist items without it cluttering the list of things I need to fix, so people can debate those types of things there.

But it's probably going to be a while, I'm rather busy at the moment.
