### ISSUE TITLE
NEC Upd77P25D and 77c25c rom progenitor ### byuu I choose you ### ^.^

### ISSUE THREAD

**Issue by darleiv** [byuu/byuu#21]
dear byuu would you have the dsp files 1 2 3 4 to use directly in the official mcu nec? I have some prehistoric necs of these stored here with uv light off all are from old traffic light terminals
. it would have to be the 10,240 byte bin starting the UPD77c25D file at the DATA address rom 2000h- until the end 27FFF
rom instruction would go up to 1FF but i don't know how to mount these rom to make it compatible with the nec official upd77d25d or upd77c25c. are there the original rom? no google, I don't have it

**Comment by Screwtapello** [comment]
Copies of the DSP1-4 ROMs are illegal to distribute, but I'm sure they're out there on the Internet somewhere.

The ROM dumps that the higan/bsnes/byuu emulators use are based on physically reading the mask ROM out of a decapped chip, and since the NEC MCUs aren't based on 8-bit bytes, there were a bunch of arbitrary decisions about how to store them in a file on disk. Therefore, the files that higan/bsnes/byuu use probably won't work with any kind of EEPROM writer, or with official NEC SDKs.

**Comment by darleiv** [comment]
friend you are wrong i'm running the byu file here so i didn't mount the rom according to what has to be 10,240 bytes to using the byk's 8k. byu primarily has the file dumped with read-only protection the decryption has read the original 10,240-byte bin file byu himself comments that it has this on the forum. follow the video of the byuu bin file running on real hardware partially using big endian. as the data rom and in 16 bits should be crashing in some graphics I didn't modify anything so I recorded https://www.youtube.com/watch?v=Bana-uTLb2I

**Comment by darleiv** [comment]
Upd has protection only in the Instruction ROM in the data rom ready

![Sem Título51](https://user-images.githubusercontent.com/33470138/76602913-aaddaa00-64ea-11ea-8bf8-c9ba67cdcd16.jpg)

**Comment by darleiv** [comment]
my doubt is that this file is in big endian 32 bits not 24 bits and the data rom too, but the data rom has to be 1024 x 16 bits, follows the mapping of the UPD true chip

24 bit Instruction ROM (0-1FFFh)
///////////// address 3,7 ... 1FFFh are Dummy
	D23-16 	D15-8	D7-0	xxxx(Dummy)
Address	0h	1h	2h	3h
	4h	5h	6h	7h
	.
	.
	.
Address	1FFCh	1FFDh	1FFEh	1FFFh
/////////////////////////////////////////////////////////////////
16-bit DATA ROM (2000h-27FF)
	D15-8	D7-0
Address	2000h	2001h	
	2002h	2003h	
	.
	.
	.
Address	27FEh	27FFh
//////////////////////////////////
If Dummy Address(3,7,A,...)  are FEh , chip is locked.

**Comment by darleiv** [comment]
PDF >>> Modified Harvard architecture with three separate memory areas
-- Program ROM (2048 x 24 bits)
-- Data ROM (1024 x 16 bits)
-- Data RAM (256 x 16 bits)

**Comment by darleiv** [comment]
with this information to assemble the original file used by nec and nintendo

**Comment by byuu** [comment]
Glad you found the answer. Nice desktop icons, by the way :p
