### ISSUE TITLE
Run-Ahead broke?

### ISSUE THREAD

**Issue by erictorres101783** [byuu/byuu#23]
I get the same number of frames per second when I turbo/fast forward whether Run-Ahead is On or Off. Also I don't notice any difference in latency.

**Comment by byuu** [comment]
It's disabled for GBA and MSX due to incompatibilities, and everywhere while fast-forwarding, which is why you don't notice.

If you don't notice it still, then you're just not sensitive to one frame of input lag which is perfectly reasonable. I'm the same usually ^-^;
