### ISSUE TITLE
cue+bin (non common case) support

### ISSUE THREAD

**Issue by mrdeathjr28** [byuu/byuu#27]
hi

some images come in cue+bin (non common case) format but dont work with byuu

![ex1](https://user-images.githubusercontent.com/6601480/76855080-59048f00-681e-11ea-95d1-ffdd350dbcc1.jpg)

![ex2](https://user-images.githubusercontent.com/6601480/76855090-5dc94300-681e-11ea-8a43-3ced092020f2.jpg)

thanks

**Comment by byuu** [comment]
I also don't intend to support split-file images, sorry. It is however much more likely than me supporting ISO+MP3, so if it's implemented, this will be done as a first priority ^-^
