### ISSUE TITLE
Sonic 2 August 1992 Special Stage loading Error 

### ISSUE THREAD

**Issue by SHODANUI** [byuu/byuu#5]
https://tcrf.net/Proto:Sonic_the_Hedgehog_2_(Genesis)/August_21st,_1992#Special_Stage

> Unlike previous builds, the Special Stage can be accessed in this build - but there's a catch. It will only load on the Kega Fusion emulator (and some other low accuracy emulators, including most Android emulators), and not modern emulators such as Genesis Plus GX or BlastEm. Presumably, it will not load on real hardware either - it seems to be an emulation error. 
This occurs in Byuu as well, potentially an oversight. 
![image](https://user-images.githubusercontent.com/57760984/75286764-f6b50180-5810-11ea-893e-cfbcba26cff1.png)

**Comment by byuu** [comment]
Wouldn't it failing to load indicate that byuu is emulating this correctly?

**Comment by SHODANUI** [comment]
> 
> 
> Wouldn't it failing to load indicate that byuu is emulating this correctly?

Seems so (Sorry if this was unclear), I lack the resources to test this on real hardware so its worth putting out there to see if others can shed light on it.

**Comment by jquestionmark** [comment]
Tested this on a Genesis model 2 with a Mega Everdrive x7 and saw similar screens/effects between byuu and the actual Genesis. With 3 different tests on the Genesis I saw different effects each time (seems to be based on the timing of when I would select the Special Stage in the stage select menu). I was able to replicate all 3 on byuu with the exception of a white screen on the actual Genesis and a black screen on byuu when the stage failed to load. 
Please let me know if you'd like me to run additional tests on hardware.
