### ISSUE TITLE
[PCE] Multiple issues using the example of Magical Chase

### ISSUE THREAD

**Issue by 6t8k** [byuu/byuu#7]
[Video](https://youtube.com/watch?v=qhRLkFWEw6c)

- During the title screen sequence, there are bars at the bottom and top edges of the screen which "smear" over the graphics and wrap around
    - The game _Mr. Heli no Daibōken_ causes a similar bar
- During the first stage, graphical glitches appear in the background
- The difficulty selection menu is glitched
- Choosing a difficulty crashes the game into a black screen (leading to the game being unplayable)

**Comment by jhlkek** [comment]
>During the title screen sequence, there are bars at the bottom and top edges of the screen which "smear" over the graphics and wrap around 

I'm pretty sure this is intentional. From byuu.org/higan:

>The way I emulate the video is rather complex: the PC Engine actually has the equivalent of video monitor modelines, which let you position and stretch the screen in various different ways. The low-level emulation of these tends to be rather demanding, and it also results in the overscan areas being visible, which is why in the screenshots for this system the video is not centered.

**Comment by byuu** [comment]
Fixed in v2.6
