### ISSUE TITLE
[WonderSwan Color] Digimon Adventure 02: D-1 Tamers - Attract/title loop graphical glitch

### ISSUE THREAD

**Issue by xdanieldzd** [byuu/byuu#9]
Digimon Adventure 02: D-1 Tamers for WonderSwan Color has a graphical issue in its attact/title loop that, as far as I know, affects every existing WonderSwan emulator. It's rather insubstantial on its own, but my guess is that it _could_ tie into undocumented background/sprite layering intricacies?

After waiting on the title screen for a while, the game will show a simple attract-type animation with Digimon sprites scrolling onto the screen from the right, staying in the center for a bit, then scrolling off the screen to the left.

The issue is that currently, the Digimon that just scrolled off-screen on the left will immediately wrap around to the right, again scroll to the center, then disappear, at which point the next Digimon will start scrolling onto the screen from the right.

A comparison of the behaviors of a SwanCrystal running the game versus byuu v1 can be seen in [this video on Twitter](https://twitter.com/xdanieldzd/status/1232014432173219842). byuu v1.1 does the same thing, as do Mednafen, WSCamp and other, older emulators.

**Comment by byuu** [comment]
Fixed in v2.1, thanks!
